#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 20 14:22:04 2018

@author: rick
"""

for n in np.arange(len(snippets))+block:
    camera_count = snip_padded[n].count('camera')
    camera_counts[n-block] = camera_count

    snippet_block = ' '.join(snip_padded[n-block:n+block])
    tfidf = TfidfVectorizer().fit_transform([words_top,snippet_block])
    pairwise_similarity = tfidf * tfidf.T
    sim_padded[n] = pairwise_similarity[0,1]
sim_padded = sim_padded[block:-block]
# Find start time of camera section
cam_occ_times = pd.DataFrame(time_points.loc[camera_counts.nonzero()])
cam_similarities = pd.Series(sim_padded)
cam_start_times = cam_occ_times.copy()
cam_start_times['similarities'] = cam_similarities.loc[camera_counts.nonzero()]
cam_start_times = cam_start_times.reset_index()
cam_start_times = cam_start_times.rename(columns = {'index':'idx'})
cam_zero = pd.DataFrame({'idx': [0], 'start_time': [0], 'similarities': [0]})
cam_start_times = pd.concat((cam_zero,cam_start_times)).reset_index(drop=True)
cam_highest_idx = cam_start_times.idx[cam_start_times.similarities[1:].idxmax()]
start_options = cam_start_times.iloc[:cam_highest_idx+1,:]
cam_delta = pd.Series(np.diff(start_options.start_time))
try:
    cam_delta_idx = cam_delta[cam_delta >= 40].index[-1]
except:
    print('Not enough camera occurences')
cam_start_time = cam_start_times.start_time.iloc[cam_delta_idx+1]
cam_start_idx = cam_start_times.idx.iloc[cam_delta_idx+1]
